public enum NotificationType {

    // Existing system notifications
    LEAVE_APPLIED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    LEAVE_CANCELLED,
    ATTENDANCE_REMINDER,
    PAYROLL_GENERATED,
    PERFORMANCE_REVIEWED,
    TRAINING_ENROLLED,
    TRAINING_COMPLETED,
    ONBOARDING_INITIATED,
    JOB_APPLICATION,
    JOB_POSTED,
    DOCUMENT_UPLOADED,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    CHECKLIST_COMPLETED,
    GENERAL,

    // Manual Admin notifications
    GREETING,
    FESTIVAL,
    ANNOUNCEMENT,
    IMPORTANT_CIRCULAR,
    GENERAL_INFORMATION
}